import { ArrowRight, Mic, Sprout, ShieldCheck, MapPin, GraduationCap, HandCoins, Users, Check, AudioLines, Route } from 'lucide-react';
import type { Language } from '../types';
export function Overview({language, onNavigate}: {language: Language; onNavigate: (tab: string) => void}) {
  const hi = language === 'hi';
  return <div className="overview">
    <div className="page-heading"><div><div className="eyebrow">SMALL STEPS. NEW POSSIBILITIES.</div><h1>{hi ? 'नमस्ते, एक नई शुरुआत करें।' : 'Your next chapter starts here.'}</h1><p>{hi ? 'आपकी रुचि से सही कौशल और काम तक — हम आपके साथ हैं।' : 'Discover work you enjoy. Build skills that matter. Find your way forward.'}</p></div><span className="welcome-symbol" aria-hidden="true"><Sprout size={32}/></span></div>
    <section className="welcome-hero">
      <div className="hero-copy"><span className="hero-kicker"><span/> A COMPANION FOR YOUR JOURNEY</span><h2>{hi ? <>आपका हुनर।<br/>आपका बेहतर कल।</> : <>Your potential.<br/>A world of <em>possibilities.</em></>}</h2><p>{hi ? 'अपनी रुचि और अनुभव बताएं। अपने लिए कौशल प्रशिक्षण और आजीविका के रास्ते जानें।' : 'Tell us a little about yourself. We’ll help you explore skills and livelihood pathways that fit your interests and your life.'}</p><button className="primary-button" onClick={() => onNavigate('voice-ask')}><Mic size={19}/>{hi ? 'बातचीत शुरू करें' : 'Talk to JeevanMitra'}<ArrowRight size={18}/></button><div className="hero-footnote"><Check size={15}/>{hi ? 'अपनी गति से · बोलकर या चुनकर' : 'At your own pace · Speak or choose'}</div></div>
      <div className="path-art" aria-hidden="true"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-sun"/><svg viewBox="0 0 440 360" className="landscape"><path d="M0 250Q130 150 260 230T460 220V360H0Z" fill="#b6c9a2"/><path d="M0 295Q140 210 300 290T460 240V360H0Z" fill="#7fa48a"/><path d="M0 325Q170 275 440 310V360H0Z" fill="#426f59"/><path d="M210 360C130 306 320 285 266 249S221 219 241 207" fill="none" stroke="#f5e7be" strokeWidth="25"/><path d="M52 291V235m0 25q-30 0-27-28 29-1 27 28m0-12q0-27 25-27 2 28-25 27" fill="#426f59" stroke="#426f59" strokeWidth="3"/></svg><div className="art-card art-card-top"><span className="art-icon"><GraduationCap size={23}/></span><span><strong>Learn a new skill</strong><small>Build on what makes you, you.</small></span></div><div className="art-card art-card-bottom"><span className="art-icon amber"><Sprout size={23}/></span><span><strong>Grow your livelihood</strong><small>A brighter future, closer to home.</small></span><span className="tiny-check"><Check size={13}/></span></div><div className="art-mic"><AudioLines size={36}/></div><span className="art-caption">A LITTLE GUIDANCE. A BIG STEP FORWARD.</span></div>
    </section>
    <section className="journey-strip" aria-label="How it works"><div className="strip-intro"><Route size={22}/><strong>A path made for you</strong><span>Three steps to get started</span></div>{[{n:'01',title:'Share your story',desc:'Your interests, skills and goals'},{n:'02',title:'Explore your options',desc:'Understand pathways that fit'},{n:'03',title:'Take the next step',desc:'Get guidance from a field worker'}].map(x=><div className="strip-step" key={x.n}><span>{x.n}</span><div><strong>{x.title}</strong><p>{x.desc}</p></div></div>)}</section>
    <div className="section-heading"><div><h2>{hi ? 'आपकी राह, आपकी पसंद' : 'Explore what’s possible'}</h2><p>Support for every part of your journey.</p></div><span>MADE FOR YOUR NEXT STEP</span></div>
    <section className="explore-grid">{[
      {id:'jobs-map',icon:MapPin,tone:'green',title:'Work closer to home',desc:'Explore local jobs and livelihood opportunities.',link:'Explore opportunities'},
      {id:'career-pathways',icon:GraduationCap,tone:'purple',title:'Learn. Practice. Grow.',desc:'Find skill pathways and see where they can take you.',link:'Discover skill pathways'},
      {id:'financial-grants',icon:HandCoins,tone:'orange',title:'Support to get started',desc:'Understand financial support for your next step.',link:'Explore financial support'},
    ].map(({id,icon:Icon,tone,title,desc,link})=><button className="explore-card" key={id} onClick={()=>onNavigate(id)}><span className={`explore-icon ${tone}`}><Icon size={23}/></span><h3>{title}</h3><p>{desc}</p><span className="card-link">{link}<ArrowRight size={17}/></span></button>)}</section>
    <section className="bottom-grid"><div className="trust-panel"><ShieldCheck size={25}/><div><h3>Clarity at every step.</h3><p>An <strong>interest match</strong> means a pathway may suit you. A <strong>verified match</strong> means a field worker has confirmed local availability.</p><span className="trust-note">This preview uses sample data. Availability is not live.</span></div></div><button className="community-panel" onClick={()=>onNavigate('community-mentors')}><span className="community-avatars"><Users size={26}/></span><span><strong>You don’t have to do it alone.</strong><small>Explore community & mentorship</small></span><ArrowRight size={20}/></button></section>
  </div>;
}
